"use client";

import React, { useMemo, forwardRef } from 'react';
import type { ReceiptData } from '@/lib/types';
import { Separator } from '@/components/ui/separator';

interface ReceiptProps {
  data: ReceiptData;
}

const Receipt = forwardRef<HTMLDivElement, ReceiptProps>(({ data }, ref) => {
  const itemTotal = useMemo(() => data.weight * data.rate, [data.weight, data.rate]);
  const previousTotal = useMemo(() => data.previousBills.reduce((acc, bill) => acc + (Number(bill.amount) || 0), 0), [data.previousBills]);
  const finalTotal = useMemo(() => itemTotal + previousTotal, [itemTotal, previousTotal]);

  const formatDate = (dateString: string) => {
    try {
      if (!dateString) return '---';
      return new Date(dateString).toLocaleDateString('ur-PK-u-nu-latn');
    } catch (e) {
      return '---';
    }
  };

  return (
    <div id="receipt-preview" ref={ref} className="w-[320px] bg-white text-black p-4 font-body text-sm rtl shadow-lg mx-auto">
      <div className="text-center mb-4">
        <h2 className="text-2xl font-bold font-headline">افضل پولٹری شاپ</h2>
        <p className="text-xs">بسم اللہ الرحمن الرحیم</p>
        <p className="mt-2">تاریخ: {formatDate(data.date)}</p>
      </div>

      <Separator className="my-2 border-dashed bg-black" />

      <div className="space-y-1">
        <div className="flex justify-between">
          <span>مرغی کا وزن (کلو)</span>
          <span>{data.weight.toLocaleString('ur-PK')}</span>
        </div>
        <div className="flex justify-between">
          <span>ریٹ (فی کلو)</span>
          <span>{data.rate.toLocaleString('ur-PK')}</span>
        </div>
        <div className="flex justify-between font-bold text-base">
          <span>کُل قیمت</span>
          <span>{itemTotal.toLocaleString('ur-PK')}</span>
        </div>
      </div>

      <Separator className="my-2 border-dashed bg-black" />
      
      {data.previousBills.length > 0 && previousTotal > 0 && (
        <>
          <h3 className="text-center font-bold mb-1">پچھلا بقایاجات</h3>
          <div className="space-y-1 text-xs">
            {data.previousBills.map(bill => (
              bill.amount > 0 && (
                <div key={bill.id} className="flex justify-between">
                  <span>تاریخ: {formatDate(bill.date)}</span>
                  <span>رقم: {Number(bill.amount).toLocaleString('ur-PK')}</span>
                </div>
              )
            ))}
          </div>
          <div className="flex justify-between font-bold mt-1 text-base">
            <span>پچھلا کُل</span>
            <span>{previousTotal.toLocaleString('ur-PK')}</span>
          </div>
          <Separator className="my-2 border-dashed bg-black" />
        </>
      )}

      <div className="text-center mt-4">
        <p className="text-lg">گرینڈ ٹوٹل</p>
        <p className="text-3xl font-bold font-headline">{finalTotal.toLocaleString('ur-PK')}</p>
      </div>

      <div className="mt-12 text-center">
        <p className="tracking-[0.2em]">--------------------</p>
        <p>دستخط</p>
      </div>
      
      <div className="text-center text-gray-500 text-[10px] mt-8">
        <p>Generated by Poultry Receipt App</p>
      </div>
    </div>
  );
});

Receipt.displayName = 'Receipt';

export default Receipt;
